/**
 * Dependencies
 */

const tokens = require('./tokens.js');
const logical = require('tailwindcss-logical');

/**
 * Config
 */

module.exports = {
  purge: false,
  important: true,
  darkMode: false,
  theme: {
    colors: tokens.color,
    borderColor: global.Object.assign({default: ''}, tokens.color),
    borderWidth: tokens.borderWidth,
    // inset: {
    //   '0': 0,
    //   'auto': 'auto',
    //   '100': '100%'
    // },
    boxShadow: tokens.shadow,
    fill: tokens.color,
    fontFamily: tokens.fontFamily,
    fontSize: tokens.fontSize,
    fontWeight: tokens.fontWeight,
    fontStyle: tokens.fontStyle,
    // height: {
    //   'auto': 'auto',
    //   'full': '100%',
    //   '90vh': '90vh',
    //   '100vh': '100vh'
    // },
    lineHeight: tokens.leading,
    // maxWidth: {
    //   '1/2': '50%',
    //   'full': '100%'
    // },
    screens: tokens.screen,
    spacing: {
      ...tokens.spacing,
      ...tokens.dimension
    },
    margin: tokens.margin,
    textColor: tokens.color,
    zIndex: tokens.z
  },
  // variants: {
  //   accessibility: ['responsive'],
  //   alignContent: ['responsive'],
  //   alignItems: ['responsive'],
  //   alignSelf: ['responsive'],
  //   animation: [],
  //   appearance: [],
  //   backgroundAttachment: [],
  //   backgroundClip: [],
  //   backgroundColor: ['responsive', 'hover', 'focus'],
  //   backgroundImage: [],
  //   backgroundOpacity: [],
  //   backgroundPosition: [],
  //   backgroundRepeat: [],
  //   backgroundSize: [],
  //   borderCollapse: [],
  //   borderColor: ['hover', 'focus'],
  //   borderOpacity: [],
  //   borderRadius: [],
  //   borderStyle: [],
  //   borderWidth: ['responsive'],
  //   boxShadow: ['responsive', 'hover', 'focus'],
  //   boxSizing: [],
  //   clear: [],
  //   cursor: [],
  //   display: ['responsive'],
  //   divideColor: [],
  //   divideOpacity: [],
  //   divideStyle: [],
  //   divideWidth: [],
  //   fill: [],
  //   flex: ['responsive'],
  //   flexDirection: ['responsive'],
  //   flexGrow: ['responsive'],
  //   flexShrink: ['responsive'],
  //   flexWrap: ['responsive'],
  //   float: [],
  //   fontFamily: [],
  //   fontSize: ['responsive'],
  //   fontSmoothing: [],
  //   fontStyle: [],
  //   fontVariantNumeric: [],
  //   fontWeight: ['responsive'],
  //   gap: ['responsive'],
  //   gradientColorStops: [],
  //   gridAutoColumns: ['responsive'],
  //   gridAutoFlow: ['responsive'],
  //   gridAutoRows: ['responsive'],
  //   gridColumn: ['responsive'],
  //   gridColumnEnd: ['responsive'],
  //   gridColumnStart: ['responsive'],
  //   gridRow: ['responsive'],
  //   gridRowEnd: ['responsive'],
  //   gridRowStart: ['responsive'],
  //   gridTemplateColumns: ['responsive'],
  //   gridTemplateRows: ['responsive'],
  //   height: [],
  //   inset: [],
  //   justifyContent: ['responsive'],
  //   justifyItems: [],
  //   justifySelf: [],
  //   letterSpacing: [],
  //   lineHeight: [],
  //   listStylePosition: [],
  //   listStyleType: [],
  //   logical: ['responsive'],
  //   margin: ['responsive'],
  //   maxHeight: [],
  //   maxWidth: ['responsive'],
  //   minHeight: ['responsive'],
  //   minWidth: [],
  //   objectFit: [],
  //   objectPosition: [],
  //   opacity: [],
  //   order: ['responsive'],
  //   outline: [],
  //   overflow: ['responsive'],
  //   overscrollBehavior: [],
  //   padding: ['responsive'],
  //   placeContent: [],
  //   placeholderColor: [],
  //   placeholderOpacity: [],
  //   placeItems: [],
  //   placeSelf: [],
  //   pointerEvents: [],
  //   position: [],
  //   resize: [],
  //   // ringColor: [],
  //   // ringOffsetColor: [],
  //   // ringOffsetWidth: [],
  //   // ringOpacity: [],
  //   // ringWidth: [],
  //   rotate: [],
  //   scale: [],
  //   skew: [],
  //   space: [],
  //   stroke: [],
  //   strokeWidth: [],
  //   tableLayout: [],
  //   textAlign: ['responsive'],
  //   textColor: ['responsive', 'hover', 'focus'],
  //   textDecoration: [],
  //   textOpacity: [],
  //   textOverflow: [],
  //   textTransform: [],
  //   transform: [],
  //   transformOrigin: [],
  //   transitionDelay: [],
  //   transitionDuration: [],
  //   transitionProperty: [],
  //   transitionTimingFunction: [],
  //   translate: [],
  //   userSelect: [],
  //   verticalAlign: [],
  //   visibility: [],
  //   whitespace: [],
  //   width: ['responsive'],
  //   wordBreak: [],
  //   zIndex: [],
  // },

  plugins: [
    logical
  ],

  // /**
  //  * These are the plugins that will be enabled in the process utility stylesheet
  //  */
  // corePlugins: [
  //   // 'preflight',
  //   // 'container',
  //   'accessibility',
  //   'alignContent',
  //   'alignItems',
  //   'alignSelf',
  //   'animation',
  //   'appearance',
  //   'backgroundAttachment',
  //   'backgroundClip',
  //   'backgroundColor',
  //   'backgroundImage',
  //   'backgroundOpacity',
  //   'backgroundPosition',
  //   'backgroundRepeat',
  //   'backgroundSize',
  //   'borderCollapse',
  //   'borderColor',
  //   'borderOpacity',
  //   'borderRadius',
  //   'borderStyle',
  //   'borderWidth',
  //   'boxShadow',
  //   'boxSizing',
  //   'clear',
  //   'cursor',
  //   'display',
  //   'divideColor',
  //   'divideOpacity',
  //   'divideStyle',
  //   'divideWidth',
  //   'fill',
  //   'flex',
  //   'flexDirection',
  //   'flexGrow',
  //   'flexShrink',
  //   'flexWrap',
  //   'float',
  //   'fontFamily',
  //   'fontSize',
  //   'fontSmoothing',
  //   'fontStyle',
  //   'fontVariantNumeric',
  //   'fontWeight',
  //   'gap',
  //   'gradientColorStops',
  //   'gridAutoColumns',
  //   'gridAutoFlow',
  //   'gridAutoRows',
  //   'gridColumn',
  //   'gridColumnEnd',
  //   'gridColumnStart',
  //   'gridRow',
  //   'gridRowEnd',
  //   'gridRowStart',
  //   'gridTemplateColumns',
  //   'gridTemplateRows',
  //   'height',
  //   'inset',
  //   'justifyContent',
  //   'justifyItems',
  //   'justifySelf',
  //   'letterSpacing',
  //   'lineHeight',
  //   'listStylePosition',
  //   'listStyleType',
  //   'margin',
  //   'maxHeight',
  //   'maxWidth',
  //   'minHeight',
  //   'minWidth',
  //   'objectFit',
  //   'objectPosition',
  //   'opacity',
  //   'order',
  //   'outline',
  //   'overflow',
  //   'overscrollBehavior',
  //   'padding',
  //   'placeContent',
  //   'placeholderColor',
  //   'placeholderOpacity',
  //   'placeItems',
  //   'placeSelf',
  //   'pointerEvents',
  //   'position',
  //   'resize',
  //   // 'ringColor',
  //   // 'ringOffsetColor',
  //   // 'ringOffsetWidth',
  //   // 'ringOpacity',
  //   // 'ringWidth',
  //   'space',
  //   'stroke',
  //   'strokeWidth',
  //   'tableLayout',
  //   'textAlign',
  //   'textColor',
  //   'textDecoration',
  //   'textOpacity',
  //   'textOverflow',
  //   'textTransform',

  //   // Transform needs to be the first module before other translate modules
  //   'transform',
  //   'transformOrigin',
  //   'translate',
  //   'rotate',
  //   'scale',
  //   'skew',

  //   'transitionDelay',
  //   'transitionDuration',
  //   'transitionProperty',
  //   'transitionTimingFunction',
  //   'userSelect',
  //   'verticalAlign',
  //   'visibility',
  //   'whitespace',
  //   'width',
  //   'wordBreak',
  //   'zIndex',
  // ]
};
